# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cse438FinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cse438FinalProject
  pod 'Firebase/Database'

end
